
## Placing an Order

POST http://localhost:1337/orders HTTP/1.1
Content-Type: "applicaton/json"
Accept: "application/json"

{
    "name": "Bob Smith",
    "address": "1212 Mockingbird Ct",
    "city": "Lakewood",
    "state": "OH",
    "zip": "44107",
    "creditCardInfo": {
        "number": "555-55-5555",
        "expiration": "06/22",
        "cvv2": "999"
    },
    "items": [
        { "id": "1", "name": "Beer", "qty": 6, "price": 1.99},
        { "id": "2", "name": "More Beer", "qty": 12, "price": 99},
        { "id": "3", "name": "Chips", "qty": 1, "price": 3.99},
    ]
}